import { PresetLocation } from './types';

export const PRESET_LOCATIONS: PresetLocation[] = [
  // --- THAILAND LANDMARKS ---
  {
    id: 'grand-palace',
    nameTh: 'วัดพระแก้ว / พระบรมมหาราชวัง',
    nameEn: 'The Grand Palace, Bangkok',
    lat: 13.7513,
    lng: 100.4926,
    category: 'landmark',
    description: 'ศูนย์กลางทางจิตใจของประเทศไทย สถาปัตยกรรมไทยอันวิจิตรตระการตา',
    icon: 'Compass',
  },
  {
    id: 'siam-paragon',
    nameTh: 'สยามพารากอน',
    nameEn: 'Siam Paragon, Bangkok',
    lat: 13.7461,
    lng: 100.5342,
    category: 'landmark',
    description: 'ศูนย์กลางการช้อปปิ้งและไลฟ์สไตล์ระดับโลกใจกลางกรุงเทพมหานคร',
    icon: 'ShoppingBag',
  },
  {
    id: 'phromthep-cape',
    nameTh: 'แหลมพรหมเทพ, ภูเก็ต',
    nameEn: 'Phromthep Cape, Phuket',
    lat: 7.7610,
    lng: 98.3064,
    category: 'landmark',
    description: 'จุดชมวิวพระอาทิตย์ตกดินที่สวยงามที่สุดและแลนด์มาร์คสำคัญของภูเก็ต',
    icon: 'Sun',
  },
  {
    id: 'tha-pae-gate',
    nameTh: 'ประตูท่าแพ, เชียงใหม่',
    nameEn: 'Tha Phae Gate, Chiang Mai',
    lat: 18.7877,
    lng: 98.9932,
    category: 'landmark',
    description: 'ประตูเมืองโบราณ จุดเช็คอินสำหรับถ่ายภาพฝูงนกพิราบยอดฮิต',
    icon: 'MapPin',
  },
  {
    id: 'pattaya-beach',
    nameTh: 'หาดพัทยากลาง',
    nameEn: 'Pattaya Beach, Chonburi',
    lat: 12.9345,
    lng: 100.8781,
    category: 'landmark',
    description: 'เมืองชายทะเลที่มีชีวิตชีวาและการพักผ่อนหย่อนใจระดับนานาชาติ',
    icon: 'Waves',
  },

  // --- GLOBAL HOTSPOTS ---
  {
    id: 'shibuya-crossing',
    nameTh: 'ห้าแยกชิบูย่า, โตเกียว',
    nameEn: 'Shibuya Crossing, Tokyo',
    lat: 35.6595,
    lng: 139.7005,
    category: 'city',
    description: 'ทางข้ามม้าลายที่มีผู้คนสัญจรพลุกพล่านที่สุดแห่งหนึ่งของโลก',
    icon: 'Users',
  },
  {
    id: 'eiffel-tower',
    nameTh: 'หอไอเฟล, ปารีส',
    nameEn: 'Eiffel Tower, Paris',
    lat: 48.8584,
    lng: 2.2945,
    category: 'city',
    description: 'สัญลักษณ์แห่งความโรแมนติกและวิศวกรรมสถาปัตยกรรมของฝรั่งเศส',
    icon: 'TowerControl', // Fallback for eiffel style
  },
  {
    id: 'times-square',
    nameTh: 'ไทมส์สแควร์, นิวยอร์ก',
    nameEn: 'Times Square, New York',
    lat: 40.7580,
    lng: -73.9855,
    category: 'city',
    description: 'ทางแยกการค้าระดับโลกและสัญลักษณ์ความบันเทิงที่ไม่เคยหลับใหล',
    icon: 'Tv',
  },
  {
    id: 'marina-bay-sands',
    nameTh: 'มารีน่าเบย์แซนด์ส, สิงคโปร์',
    nameEn: 'Marina Bay Sands, Singapore',
    lat: 1.2834,
    lng: 103.8607,
    category: 'city',
    description: 'สถาปัตยกรรมอาคารทรงเรือสามแฝดและคาสิโนระดับพรีเมียม',
    icon: 'Building',
  },
  {
    id: 'sydney-opera-house',
    nameTh: 'ซิดนีย์โอเปร่าเฮาส์',
    nameEn: 'Sydney Opera House, Australia',
    lat: -33.8568,
    lng: 151.2153,
    category: 'landmark',
    description: 'สโมสรโรงละครทรงเปลือกหอยอันเป็นสัญลักษณ์สำคัญของทวีปออสเตรเลีย',
    icon: 'Music',
  },
  {
    id: 'london-big-ben',
    nameTh: 'หอนาฬิกาบิ๊กเบน, ลอนดอน',
    nameEn: 'Big Ben, London',
    lat: 51.5007,
    lng: -0.1246,
    category: 'city',
    description: 'หอนาฬิกาประจำรัฐสภาอังกฤษ สัญลักษณ์ประวัติศาสตร์อันสง่างาม',
    icon: 'Clock',
  },
  {
    id: 'giza-pyramids',
    nameTh: 'มหาพีระมิดกิซา, อียิปต์',
    nameEn: 'Pyramids of Giza, Egypt',
    lat: 29.9792,
    lng: 31.1342,
    category: 'landmark',
    description: 'หนึ่งในเจ็ดสิ่งมหัศจรรย์ของโลกยุคโบราณที่ยังคงยืนหยัดทิวทัศน์ทะเลทราย',
    icon: 'Triangle',
  }
];
